apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  generators:
    - directory:
        path: tenants/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: tenants
      source:
        repoURL: https://github.com/7M-Cloud/my-k3s-gitops.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true