apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-workloads
  namespace: argocd
spec:
  generators:
    - directory:
        # Targets app folders (e.g., tenants/monitoring/grafana)
        path: tenants/*/*
        exclude:
          - tenants/monitoring/namespace.yaml
          - tenants/platform-team/namespaces.yaml
  template:
    metadata:
      name: 'tenant-{{path.basename}}'
    spec:
      project: tenants
      source:
        repoURL: https://github.com/7M-Cloud/my-k3s-gitops.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        # Dynamically picks the namespace (e.g., 'monitoring' or 'platform-team')
        namespace: '{{path.segments[1]}}' 
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true