apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-workloads
  namespace: argocd
spec:
  generators:
    - directory:
        path: tenants/**/*
        exclude:
          - tenants/monitoring/namespace.yaml
          - tenants/platform-team/namespaces.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: tenants
      source:
        repoURL: https://github.com/7M-Cloud/my-k3s-gitops.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        # This tells ArgoCD to use the parent folder name as the target namespace
        namespace: '{{path.segments[1]}}' 
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true # 👈 This automatically creates the namespace if missing