grafana:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 15d

    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: prometheus.localhost
          paths:
            - /

alertmanager:
  enabled: true

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: alertmanager.localhost
        paths:
          - /