prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.localhost

grafana:
  enabled: false

alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alertmanager.localhost
