grafana:
  enabled: false

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - prometheus.localhost
    paths:
      - /

alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - alertmanager.localhost
    paths:
      - /