backstage:
  appConfig:
    app:
      title: "K3s Platform AI Portal"
      baseUrl: http://backstage.localhost
    backend:
      baseUrl: http://backstage.localhost
      listen:
        port: 7007
ingress:
  enabled: true
  className: traefik
  host: backstage.localhost
