global:
  imageRegistry: ""

backstage:
  image:
    registry: ""
    repository: backstage-ai
    tag: "1.0"
    pullPolicy: Never

  appConfig:
    app:
      title: "K3s Platform AI Portal"
      baseUrl: http://backstage.localhost

    backend:
      baseUrl: http://backstage.localhost
      listen:
        port: 7007

    organization:
      name: "Local Lab"

ingress:
  enabled: true
  className: traefik
  host: backstage.localhost