apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: "Management project for cluster infrastructure"
  sourceRepos:
    - '*' 
  destinations:
    - namespace: '*' # 🌐 Allows platform tools to reach any namespace
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*' # 🏗️ Allows creating Namespaces, CRDs, and RBAC