grafana:
  enabled: true
  
  # Persistence is key for a home lab so you don't lose dashboards
  persistence:
    enabled: true
    storageClassName: local-path # Default for K3s
    size: 2Gi

  # Define your admin password (or use a secret reference)
  adminPassword: "password"

  # Automatically setup data sources (e.g., Prometheus)
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

  
  ingress:
    enabled: true
    # For K3s Traefik, this is the standard class name
    ingressClassName: traefik 
    annotations:
      # Optional: Force SSL redirect if you have cert-manager setup later
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - grafana.local # Change this to your desired domain or node IP
    path: /
    pathType: Prefix
