service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - grafana.localhost
  path: /
  pathType: Prefix

# 👇 ADD THIS BLOCK TO FIX THE ERROR
rbac:
  pspEnabled: false
  # values.yaml
additionalDataSources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
